// <auto-generated />
using System;
using Bdtheque.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bdtheque.Infrastructure.Migrations
{
    [DbContext(typeof(BdthequeDbContext))]
    [Migration("20260929175122_AddEditionVisual")]
    partial class AddEditionVisual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid");

                    b.HasKey("AlbumId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AlbumGenres", (string)null);
                });

            modelBuilder.Entity("AlbumUniverse", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversesId")
                        .HasColumnType("uuid");

                    b.HasKey("AlbumId", "UniversesId");

                    b.HasIndex("UniversesId");

                    b.ToTable("AlbumUniverses", (string)null);
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EndVolumeNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstPublicationMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstPublicationYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManualSortKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialIssue")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("SortKey")
                        .HasMaxLength(510)
                        .HasColumnType("character varying(510)");

                    b.Property<int?>("StartVolumeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SortKey");

                    b.ToTable("Albums", t =>
                        {
                            t.HasCheckConstraint("CK_Albums_ManualSortKeyRequiresTitle", "\"IsManualSortKey\" = false OR \"Title\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Albums_PublicationMonthRange", "\"FirstPublicationMonth\" IS NULL OR \"FirstPublicationMonth\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_Albums_PublicationMonthRequiresYear", "\"FirstPublicationMonth\" IS NULL OR \"FirstPublicationYear\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Albums_PublicationYearPositive", "\"FirstPublicationYear\" IS NULL OR \"FirstPublicationYear\" > 0");

                            t.HasCheckConstraint("CK_Albums_SortKeyNotBlank", "\"SortKey\" IS NULL OR LENGTH(TRIM(\"SortKey\")) > 0");

                            t.HasCheckConstraint("CK_Albums_SortKeyPresenceMatchesTitle", "(\"Title\" IS NULL) = (\"SortKey\" IS NULL)");

                            t.HasCheckConstraint("CK_Albums_TitleNotBlank", "\"Title\" IS NULL OR LENGTH(TRIM(\"Title\")) > 0");

                            t.HasCheckConstraint("CK_Albums_TitleRequiredWithoutSeries", "\"SeriesId\" IS NOT NULL OR LENGTH(TRIM(COALESCE(\"Title\", ''))) > 0");

                            t.HasCheckConstraint("CK_Albums_VolumeNumberPositive", "\"VolumeNumber\" IS NULL OR \"VolumeNumber\" > 0");

                            t.HasCheckConstraint("CK_Albums_VolumeRangeBothOrNeither", "(\"StartVolumeNumber\" IS NULL) = (\"EndVolumeNumber\" IS NULL)");

                            t.HasCheckConstraint("CK_Albums_VolumeRangeOmnibusOnly", "\"StartVolumeNumber\" IS NULL OR \"Type\" = 2");

                            t.HasCheckConstraint("CK_Albums_VolumeRangeOrder", "\"StartVolumeNumber\" IS NULL OR \"StartVolumeNumber\" <= \"EndVolumeNumber\"");

                            t.HasCheckConstraint("CK_Albums_VolumeRangeStartPositive", "\"StartVolumeNumber\" IS NULL OR \"StartVolumeNumber\" > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pseudonym")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors", t =>
                        {
                            t.HasCheckConstraint("CK_Authors_LastNameOrPseudonym", "COALESCE(LENGTH(TRIM(\"LastName\")), 0) > 0 OR COALESCE(LENGTH(TRIM(\"Pseudonym\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AlbumId", "Role", "AuthorId")
                        .IsUnique()
                        .HasFilter("\"AlbumId\" IS NOT NULL");

                    b.HasIndex("SeriesId", "Role", "AuthorId")
                        .IsUnique()
                        .HasFilter("\"SeriesId\" IS NOT NULL");

                    b.ToTable("Contributions", t =>
                        {
                            t.HasCheckConstraint("CK_Contributions_ExactlyOneOfAlbumOrSeries", "(\"AlbumId\" IS NOT NULL) <> (\"SeriesId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AcquisitionAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<string>("AcquisitionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<int?>("AcquisitionMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Binding")
                        .HasColumnType("integer");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("Condition")
                        .HasColumnType("integer");

                    b.Property<int?>("Format")
                        .HasColumnType("integer");

                    b.Property<bool>("IsColor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDedicated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecondHand")
                        .HasColumnType("boolean");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Orientation")
                        .HasColumnType("integer");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<string>("PersonalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublisherCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReadingDirection")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("PublisherCollectionId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Editions", t =>
                        {
                            t.HasCheckConstraint("CK_Editions_AcquisitionAmountCurrencyTogether", "(\"AcquisitionAmount\" IS NULL) = (\"AcquisitionCurrency\" IS NULL)");

                            t.HasCheckConstraint("CK_Editions_AcquisitionAmountPositive", "\"AcquisitionAmount\" IS NULL OR \"AcquisitionAmount\" > 0");

                            t.HasCheckConstraint("CK_Editions_AcquisitionModeRequiredForDateOrPrice", "\"AcquisitionMode\" IS NOT NULL OR (\"AcquisitionDate\" IS NULL AND \"AcquisitionAmount\" IS NULL)");

                            t.HasCheckConstraint("CK_Editions_FreeRequiresNoAmount", "\"IsFree\" = false OR \"AcquisitionAmount\" IS NULL");

                            t.HasCheckConstraint("CK_Editions_PageCountPositive", "\"PageCount\" IS NULL OR \"PageCount\" > 0");

                            t.HasCheckConstraint("CK_Editions_PublicationYearPositive", "\"PublicationYear\" IS NULL OR \"PublicationYear\" > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.EditionVisual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaReference")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EditionId", "Type", "DisplayOrder");

                    b.ToTable("EditionVisuals", t =>
                        {
                            t.HasCheckConstraint("CK_EditionVisuals_DisplayOrderNotNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_EditionVisuals_MediaReferenceNotBlank", "COALESCE(LENGTH(TRIM(\"MediaReference\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Genres", t =>
                        {
                            t.HasCheckConstraint("CK_Genres_LabelNotBlank", "COALESCE(LENGTH(TRIM(\"Label\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", t =>
                        {
                            t.HasCheckConstraint("CK_Publishers_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.PublisherCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId", "Name")
                        .IsUnique();

                    b.ToTable("PublisherCollections", t =>
                        {
                            t.HasCheckConstraint("CK_PublisherCollections_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ExcludeFromMissingVolumes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManualSortKey")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasMaxLength(510)
                        .HasColumnType("character varying(510)");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int?>("TemplateBinding")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateEditionCategory")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateFormat")
                        .HasColumnType("integer");

                    b.Property<bool?>("TemplateIsColor")
                        .HasColumnType("boolean");

                    b.Property<int?>("TemplateOrientation")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplatePublisherCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplatePublisherId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TemplateReadingDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("TheoreticalVolumeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SortKey");

                    b.HasIndex("TemplatePublisherCollectionId");

                    b.HasIndex("TemplatePublisherId");

                    b.ToTable("Series", t =>
                        {
                            t.HasCheckConstraint("CK_Series_SortKeyNotBlank", "COALESCE(LENGTH(TRIM(\"SortKey\")), 0) > 0");

                            t.HasCheckConstraint("CK_Series_TemplateCollectionRequiresPublisher", "\"TemplatePublisherCollectionId\" IS NULL OR \"TemplatePublisherId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Series_TheoreticalVolumeCountPositive", "\"TheoreticalVolumeCount\" IS NULL OR \"TheoreticalVolumeCount\" > 0");

                            t.HasCheckConstraint("CK_Series_TitleNotBlank", "COALESCE(LENGTH(TRIM(\"Title\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Universes", t =>
                        {
                            t.HasCheckConstraint("CK_Universes_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");

                            t.HasCheckConstraint("CK_Universes_NoSelfParent", "\"ParentId\" IS NULL OR \"ParentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("GenreSeries", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesGenres", (string)null);
                });

            modelBuilder.Entity("SeriesUniverse", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversesId")
                        .HasColumnType("uuid");

                    b.HasKey("SeriesId", "UniversesId");

                    b.HasIndex("UniversesId");

                    b.ToTable("SeriesUniverses", (string)null);
                });

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumUniverse", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Universe", null)
                        .WithMany()
                        .HasForeignKey("UniversesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Album", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Contribution", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bdtheque.Domain.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Album");

                    b.Navigation("Author");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Edition", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.PublisherCollection", "PublisherCollection")
                        .WithMany()
                        .HasForeignKey("PublisherCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bdtheque.Domain.Entities.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Publisher");

                    b.Navigation("PublisherCollection");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.EditionVisual", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Edition", "Edition")
                        .WithMany("Visuals")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.PublisherCollection", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Collections")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Series", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.PublisherCollection", "TemplatePublisherCollection")
                        .WithMany()
                        .HasForeignKey("TemplatePublisherCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bdtheque.Domain.Entities.Publisher", "TemplatePublisher")
                        .WithMany()
                        .HasForeignKey("TemplatePublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TemplatePublisher");

                    b.Navigation("TemplatePublisherCollection");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Universe", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GenreSeries", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeriesUniverse", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Universe", null)
                        .WithMany()
                        .HasForeignKey("UniversesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Edition", b =>
                {
                    b.Navigation("Visuals");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
