// <auto-generated />
using System;
using Bdtheque.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bdtheque.Infrastructure.Migrations
{
    [DbContext(typeof(BdthequeDbContext))]
    partial class BdthequeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bdtheque.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pseudonym")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Authors_LastNameOrPseudonym", "COALESCE(LENGTH(TRIM(\"LastName\")), 0) > 0 OR COALESCE(LENGTH(TRIM(\"Pseudonym\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Genres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Genres_LabelNotBlank", "COALESCE(LENGTH(TRIM(\"Label\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Publishers_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.PublisherCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId", "Name")
                        .IsUnique();

                    b.ToTable("PublisherCollections", null, t =>
                        {
                            t.HasCheckConstraint("CK_PublisherCollections_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ExcludeFromMissingVolumes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManualSortKey")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasMaxLength(510)
                        .HasColumnType("character varying(510)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TemplateBinding")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TemplateCondition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TemplateEditionCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TemplateFormat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("TemplateIsColor")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateOrientation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TemplatePublisherCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplatePublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateReadingDirection")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TheoreticalVolumeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SortKey");

                    b.HasIndex("TemplatePublisherCollectionId");

                    b.HasIndex("TemplatePublisherId");

                    b.ToTable("Series", null, t =>
                        {
                            t.HasCheckConstraint("CK_Series_SortKeyNotBlank", "COALESCE(LENGTH(TRIM(\"SortKey\")), 0) > 0");

                            t.HasCheckConstraint("CK_Series_TemplateCollectionRequiresPublisher", "\"TemplatePublisherCollectionId\" IS NULL OR \"TemplatePublisherId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Series_TheoreticalVolumeCountPositive", "\"TheoreticalVolumeCount\" IS NULL OR \"TheoreticalVolumeCount\" > 0");

                            t.HasCheckConstraint("CK_Series_TitleNotBlank", "COALESCE(LENGTH(TRIM(\"Title\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Universes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Universes_NameNotBlank", "COALESCE(LENGTH(TRIM(\"Name\")), 0) > 0");

                            t.HasCheckConstraint("CK_Universes_NoSelfParent", "\"ParentId\" IS NULL OR \"ParentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("GenreSeries", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesGenres", (string)null);
                });

            modelBuilder.Entity("SeriesUniverse", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversesId")
                        .HasColumnType("uuid");

                    b.HasKey("SeriesId", "UniversesId");

                    b.HasIndex("UniversesId");

                    b.ToTable("SeriesUniverses", (string)null);
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.PublisherCollection", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Collections")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Series", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.PublisherCollection", "TemplatePublisherCollection")
                        .WithMany()
                        .HasForeignKey("TemplatePublisherCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bdtheque.Domain.Entities.Publisher", "TemplatePublisher")
                        .WithMany()
                        .HasForeignKey("TemplatePublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TemplatePublisher");

                    b.Navigation("TemplatePublisherCollection");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Universe", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GenreSeries", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeriesUniverse", b =>
                {
                    b.HasOne("Bdtheque.Domain.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bdtheque.Domain.Entities.Universe", null)
                        .WithMany()
                        .HasForeignKey("UniversesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Bdtheque.Domain.Entities.Universe", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
