using System.Runtime.CompilerServices;

// Required for Bdtheque.Api.Tests to use WebApplicationFactory<Program>
// (the Program class generated by top-level statements is internal).
[assembly: InternalsVisibleTo("Bdtheque.Api.Tests")]
